# coding: utf-8
require '../../config'
require 'cantata'

require_relative 'scatter_plots'
require_relative 'box_violin_dot'
require_relative 'one_variable_continuous/histogram_density'
require_relative 'scatter_gg'
require_relative 'one_variable_continuous/density_gg'
require_relative 'one_variable_continuous/geom_area'
require_relative 'one_variable_continuous/geom_density'
require_relative 'one_variable_continuous/geom_dotplot'
require_relative 'one_variable_continuous/geom_freqpoly'
require_relative 'one_variable_continuous/geom_histogram'
require_relative 'one_variable_continuous/stat'
require_relative 'one_variable_discrete/bar'
require_relative 'two_variables_cont_cont/geom_point'
require_relative 'two_variables_cont_cont/geom_smooth'
require_relative 'two_variables_cont_cont/misc'

